;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = modules.ini

[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[color]
bg = #2f354b
bg-alt = #BF1D1F28
fg = #FDFDFD

trans = #00000000
white = #FFFFFF
black = #000000

red = #F37F97
pink = #EC407A
purple = #C574DD
blue = #8897F4
cyan = #79E6F3
teal = #00B19F
green = #5ADECD
lime = #B9C244
yellow = #F2A272
amber = #FBC02D
orange = #E57C46
brown = #AC8476
grey = #8C8C8C
indigo = #6C77BB
blue-gray = #6D8895

[bar/pam1]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 2.5%
height = 40

offset-x = 2%
offset-y = 8

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 0

module-margin-left = 0
module-margin-right = 0

font-0 = HackGen35 Console NF:size=14;3

modules-left =
modules-center = launcher
modules-right =

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll = ns-resize

[bar/pam2]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = false

width = 17%
height = 40

offset-x = 5%
offset-y = 8

background = ${color.bg-alt}
foreground = ${color.fg}

radius = 6

line-size = 2
line-color = ${color.blue}

border-size = 2
border-color = ${color.bg}

padding = 2

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = HackGen35 Console NF:size=8;2
; Icons
font-1 = "JetBrainsMono:style=Regular:pixelsize=12;3"

modules-left =
modules-center = i3
modules-right =

separator =
dim-value = 1.0

;locale = es_MX.UTF-8

wm-restack = i3
enable-ipc = true

cursor-click = pointer
cursor-scroll = ns-resize

[bar/example]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = HackGen35 Console NF:size=10;2

modules-left = xworkspaces xwindow
modules-right = filesystem pulseaudio xkeyboard memory_bar cpu_bar wlan date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3
override-redirect = true

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
