"$schema" = 'https://starship.rs/config-schema.json'

palette = "neovim"

format = """
[░▒▓](purple)\
$os\
$username\
[](bg:blue fg:purple)\
$directory\
[](fg:blue bg:muted)\
$git_branch\
$git_status\
[](fg:muted bg:background)\
$c\
$nodejs\
$bun\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:background bg:comment)\
$docker_context\
$conda\
$time\
[ ](fg:comment)\
\n$character"""

[palettes.neovim]
background = "#111318"
foreground = "#DCD7BA"
muted = "#54546D"
comment = "#727169"
blue = "#7E9CD8"
purple = "#957FB8"
green = "#98BB6C"
yellow = "#E6C384"
orange = "#FFA066"

[directory]
style = "fg:background bg:blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[username]
show_always = true
style_user = "bg:purple fg:background"
style_root = "bg:purple fg:background"
format = '[ $user ]($style)'

[git_branch]
symbol = ""
style = "bg:muted"
format = '[[ $symbol $branch ](fg:foreground bg:muted)]($style)'

[git_status]
style = "bg:muted"
format = '[[($all_status$ahead_behind )](fg:green bg:muted)]($style)'

[nodejs]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:green bg:background)]($style)'

[c]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:blue bg:background)]($style)'

[cpp]
disabled = false
symbol = ""
style = "bg:background"
format = '[[ $symbol $name ($version) ](fg:blue bg:background)]($style)'

[bun]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:yellow bg:background)]($style)'

[rust]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:orange bg:background)]($style)'

[golang]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:blue bg:background)]($style)'

[php]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:purple bg:background)]($style)'

[java]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:orange bg:background)]($style)'

[kotlin]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:purple bg:background)]($style)'

[haskell]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:purple bg:background)]($style)'

[python]
symbol = ""
style = "bg:background"
format = '[[ $symbol ($version) ](fg:yellow bg:background)]($style)'

[docker_context]
symbol = ""
style = "bg:comment"
format = '[[ $symbol ($context) ](fg:blue bg:comment)]($style)'

[conda]
style = "bg:comment"
format = '[[ $symbol ($environment) ](fg:green bg:comment)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:comment"
format = '[[  $time ](fg:foreground bg:comment)]($style)'

[os]
style = "bg:purple fg:background"
format = "[ $symbol ]($style)"
disabled = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold orange)"
vimcmd_symbol = "[❮](bold blue)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_visual_symbol = "[❮](bold yellow)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
